# Tools downloaded by Aftman
[tools]
rojo = "rojo-rbx/rojo@7.3.0"
wally = "UpliftGames/wally@0.3.2"
selene = "Kampfkarren/selene@0.25.0"
stylua = "JohnnyMorganz/StyLua@0.18.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.26.0"
