[package]
name = "constant/guncast"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index" 
realm = "shared"

[dependencies]
Maid = "coiorevent8/maid@3.4.0" # Maid is a library for managing objects in Lua.
Promise = "evaera/promise@4.0.0" # Promise is a library for handling asynchronous operations in Lua.