[package]
name = "coiorevent8/maid"
description = "Maid class"
version = "3.4.0"
license = "Apache-2.0"
authors = ["coior"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"